[package]
name = "distilled"
version = "0.1.0"
authors = ["Mikaël Fourrier <mikael.fourrier@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "1.0.0-alpha3"
wasmer-compiler-cranelift = "1.0.0-alpha3"
wasmer-engine-jit = "1.0.0-alpha3"
types = {path = "types"}
nanoserde = "0.1.19"
anyhow = "1.0.32"

[workspace]
members = ["types", "wasm"]
