[package]
name = "distilled"
version = "0.1.0"
authors = ["Mikaël Fourrier <mikael.fourrier@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = { version = "1.0.0-alpha3", default-features = false, optional = false, features = ["jit", "cranelift"] }
wasm = { path = "wasm" }
nanoserde = "0.1.19"
anyhow = "1.0.32"
crossbeam-channel = "0.4.4"

[workspace]
members = ["distilled-derive", "wasm"]
